/** Central place for app paths so links don't drift as routes evolve. */
export const routes = {
  home: "/",
  login: "/auth?mode=login",
  signup: "/auth?mode=signup",
  onboarding: "/onboarding",
  dashboard: "/dashboard",
  investigations: "/investigations",
  newInvestigation: "/investigations/new",
  clarifyingQuestions: "/investigations/new/questions",
  investigationPlan: "/investigations/new/plan",
  investigation: (id: string, tab?: string) => `/investigations/${id}${tab ? `/${tab}` : ""}`,
  research: "/research",
  customers: "/customers",
  problems: "/problems",
  opportunities: "/opportunities",
  decisions: "/decisions",
  validation: "/validation",
  memory: "/memory",
  dataSources: "/data-sources",
  context: "/context",
  settings: "/settings",
} as const;
